import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { cn } from "../utils/common-utils";
import { QueryProvider } from "../components/query/query.provider";
import { AuthProvider } from "../components/auth/auth.provider";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"h-full"}>
      <body className={cn("h-full", font.className)}>
        <div className="flex flex-col min-h-full bg-[url('/background.png')] bg-bottom bg-contain bg-no-repeat">
          <AuthProvider>
            <QueryProvider>
              {children}
              <ToastContainer position={"top-center"} />
            </QueryProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
